### ISSUE TITLE
Error: Identifier not found "TSize"

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgragui#1]
Hello.

I try to compile following your instruction, but get that error:

```
Compiling /home/fred/Downloads/bgragui-dev-bgragui/bgragui/bgbuttondrawer.pas
bgbuttondrawer.pas(72,7) Error: Identifier not found "TSize"
bgbuttondrawer.pas(72,12) Error: Error in type definition
```

Thanks.

By the way, you are not obliged to copy all the source into /msegui/lib/, you may also define the search directory with Project Options:

![Capture d’écran_2020-05-11_11-48-28](https://user-images.githubusercontent.com/3421249/81548341-7026af80-937d-11ea-9d6b-d919d231c723.png)

**Comment by fredvs** [comment]
Hola.

OK, for `TSize`, it is fixed adding "`Types`" in uses section of  `BGButtonDrawer.pas`

But now there is a other error:

> bgbutton.pas(56,26) Error: Incompatible type for arg no. 3: Got "ShortInt", expected "Boolean"

---->

` fbgra.Draw(canvas, 0, 0);`

;-(

**Comment by fredvs** [comment]
IMHO, when all is ok, I think the best would be to create in MSEide the `bgragui` tab and all the components in `Component Palette`.

So people have to add the required `BGRA***` directory in the search path in project option if they want use one of the  `bgragui` components .

For `ideU` maybe the source of `BGRA***` can be included in `ideU` source.
But maybe too it is better to have all the `BGRA***` source independent and do, like for MSEide: create the BGRAgui tab + components and use the external source of  `BGRA***`, so if there is new commit in `BGRAgui` source, people have more independence.

**Comment by fredvs** [comment]
Re-re-hola.

IMHO, the simpler would be to have only one directory `BGRABitmap` and inside all his child, like BGRAgui, BGRAcontrols, ... etc.

This because doing this you only need a unique macro: ` ${BGRABITMAPDIR}` (that exists already in ideU as global macro).

**Comment by fredvs** [comment]
Here how to create a global macro: in Settings, Configure MSEide:

![Capture d’écran_2020-05-11_13-29-21](https://user-images.githubusercontent.com/3421249/81557224-e500e600-938b-11ea-9423-f1541c96ee96.png)

And then in your project, you may use it like this:

![Capture d’écran_2020-05-11_13-31-46](https://user-images.githubusercontent.com/3421249/81557270-fc3fd380-938b-11ea-8d94-768372757a8d.png)

OK, I let you in peace.

Have fun!

Fre;D

**Comment by lainz** [comment]
Hi, thanks for all the suggestions, when I have time I will check.

Maybe I will switch to a release compiler for mseide instead of trunk, to ensure things are working, like the Types not found, seems that is directly available in trunk without the uses, but not on current release of FPC.

**Comment by fredvs** [comment]
> Maybe I will switch to a release compiler for mseide instead of trunk,

Normally, msegui is compatible with fpc trunk and it should not have problems.

> , but not on current release of FPC.

I did the test with fpc 3.2.0 RC1

**Comment by lainz** [comment]
Ok, I will download 3.2.0 RC1 to test.

**Comment by fredvs** [comment]
> like the Types not found, 

Hum, maybe it is due to the fact that MSEgui has his own `msetypes` and if you use fpc declartion-types, you need to add `types`

**Comment by lainz** [comment]
Ok, yes I prefer to use FPC types for the drawer unit, for the control itself there are no problems.

**Comment by fredvs** [comment]
> Ok, yes I prefer to use FPC types for the drawer unit,

Yes, of course.
Is it a problem for you to add  `types` , do it cause conflict if you use the code for LCL for example?

**Comment by lainz** [comment]
I've added the Types unit in the last commit.

I have a question, for example if I add a global macro, like you said {BGRAGUIDIR} for my ide. Then you open the project in your IDE and you don't have the global macro. What happens then? I should add in the readme that the user must configure first that macro, instead of copying the units? Or both are interchangeable, say I can copy the directory or use the macro?

I say for the examples folder that comes with bgragui.
I mean if the macro is not set, there is an error displayed or the project will compile anyways?

**Comment by lainz** [comment]
I will check that later. But I think is better using the macro than copying the directory. I'm copying every time I'm making a change, so better don't do that =)

**Comment by lainz** [comment]
> Hola.
> 
> OK, for `TSize`, it is fixed adding "`Types`" in uses section of `BGButtonDrawer.pas`
> 
> But now there is a other error:
> 
> > bgbutton.pas(56,26) Error: Incompatible type for arg no. 3: Got "ShortInt", expected "Boolean"
> 
> ---->
> 
> ` fbgra.Draw(canvas, 0, 0);`
> 
> ;-(

What happens if you do like this:

`fbgra.Draw(canvas, 0, 0, False)`

**Comment by fredvs** [comment]
>  Then you open the project in your IDE and you don't have the global macro. What happens then?

It will simply fail to compile with some errors "file not found"...

> I should add in the readme that the user must configure first that macro, instead of copying the units?

Imho, it is the good way to do.
One note in readme.txt in **BIG** :

> Please, create first a global macro BGRAGUIDIR that point to the root directory of BGRAgui.
> For this, on menu "Settings" add in "name": BGRAGUIDIR and in value, for example /home/you/bgragui

For ideU, I will add a integrated `BGRAGUIDIR` macro, like for `FPGUIDIR`, `LCLDIR` and `BGABITMAPDIR`.

> But I think is better using the macro than copying the directory.

I think it is better too.

**Comment by fredvs** [comment]
> What happens if you do like this:
> fbgra.Draw(canvas, 0, 0, False)

Aaargh, I get this:

`bgbutton.pas(56,20) Error: Incompatible type for arg no. 1: Got "MSEGRAPHICS.tcanvas", expected "BGRAGRAPHICS.TCanvas"`

So it is a problem of conflict with classes.
Circular had the same problem with BGRABitmap.

I hope he will see this because he knows how to fix it.
I will try but sure Circular is much better than me.

**Comment by circular17** [comment]
Well in theory if you have the define BGRABITMAP_USE_MSEGUI that would not happen.

**Comment by fredvs** [comment]
By the way, is it ok with your system, does it accept  `fbgra.Draw(canvas, 0, 0)`, can you compile it?
If yes, could you give me the command line that you use?
On project option, make, click on "Show command line"

![image](https://user-images.githubusercontent.com/3421249/81592963-0dee9e80-93bf-11ea-9b70-e25b9e99f04b.png)

**Comment by fredvs** [comment]
> Well in theory if you have the define BGRABITMAP_USE_MSEGUI that would not happen.

Ooops, I forgot the theory...

I will try with `-dBGRABITMAP_USE_MSEGUI`

Write you later....

**Comment by fredvs** [comment]
Hum, here adding -dBGRABITMAP_USE_MSEGUI in compiler make option did not help.

**Comment by lainz** [comment]
I did not define nothing. I just used the latest mseide that says is compatible with BGRABitmap, maybe is defined in the ide automatically?

Or maybe is because I copied the entire bgrabitmap folder inside lib/common?

**Comment by fredvs** [comment]
> I just used the latest mseide that says is compatible with BGRABitmap, maybe is defined in the ide automatically?

We did not try to use BGRABitmap for MSEide himself, only for some demos.

So you confirm that you can compile the code that is in bgragui github without problems.

That is a excellent news.

Now, why it is not working for me, maybe it is, like you said, because of folders location?
I will try but I have doubt.

**Comment by fredvs** [comment]
> Or maybe is because I copied the entire bgrabitmap folder inside lib/common?

Yep, you get it, indeed after copy  bgrabitmap folder inside lib/common it works:

![Capture d’écran_2020-05-11_20-29-59](https://user-images.githubusercontent.com/3421249/81597592-40e86080-93c6-11ea-89e3-f95c364b39e9.png)

So, maybe there is a hierarchy that must be respected in the list of search directories?

Hum, strange, I will try to change the order, first BGRAbitmap directory, then MSEgui/lib directoriy?

OK, I let that for later (but it is very strange).

**Comment by fredvs** [comment]
Hola.

Sorry, it was my fault, the macro that I used pointed to a old BGRABitmap code.
Now all is ok, no problem of hierarchy or something else.

I apologize for the noise.
