### ISSUE TITLE
Transparency doesn't work in custom control

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgragui#2]
I've done a simple test, copying the control TBGRAFlashProgressBar that has a transparent border and it is displayed as black. Compare how it should look in the original TBGRAFlashProgressBar from BGRAControls.

**Comment by fredvs** [comment]
> Compare how it should look in the original TBGRAFlashProgressBar from BGRAControls.

Not sure to understand, is it related with the mse-tbgbutton , where is the original?

**Comment by fredvs** [comment]
Ooops, you did new commits.
OK, I will check this tonight.

**Comment by lainz** [comment]
I've fixed it, seems that it uses the color property as background for the component, so components are not really transparent, they uses the background property.

**Comment by fredvs** [comment]
> seems that it uses the color property as background for the component,

I dont know if it can help, but for MSEgui there is the color "cl_transparent" that works for background too.

[EDIT] And "cl_none" too.

**Comment by lainz** [comment]
> > seems that it uses the color property as background for the component,
> 
> I dont know if it can help, but for MSEgui there is the color "cl_transparent" that works for background too.
> 
> [EDIT] And "cl_none" too.

Cool, cl_transparent is working fine. The idea is to place controls in top of images for example, and keep the transparency.

**Comment by fredvs** [comment]
>  The idea is to place controls in top of images for example, and keep the transparency.

In fact, some properties work like layers.
The main property "color" is the first layer, then property "face-fade", then "face-image", then others depends of widget.

As far, it is what I understood.

**Comment by fredvs** [comment]
But you are already many steps further, I talk you about the "build-in" properties of the MSEgui widgets.
You are talking about adding new properties so, sorry, I have to jump into this deeper.
Tonight I will try your last commits.
