### ISSUE TITLE
About the drawers

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgragui#3]
I think we can speed it up using CSS controls already made
https://forum.lazarus.freepascal.org/index.php/topic,36502.msg360149.html#msg360149

But drawing with BGRABitmap
https://github.com/pst2d/csscontrols/issues/3

So we can create more complex controls more easily. With CSS properties like.

**Comment by fredvs** [comment]
What is CSS, what does CSS that BGRABitmap does not do?
What are the advantages of CSS?

**Comment by lainz** [comment]
Hi, check this demo:
https://forum.lazarus.freepascal.org/index.php/topic,36502.msg360149.html#msg360149

Is a demo made to beat my own demo (using BGRAControls)
https://forum.lazarus.freepascal.org/index.php/topic,36502.msg359305.html#msg359305

You can build things like web pages with it.
But what is more interesting, you can build custom controls mixing several CSS controls in a new one.

**Comment by lainz** [comment]
Is not replacing BGRABitmap, but using BGRABitmap together with that package. For that I asked the author to see if he can use BGRABitmap to draw his controls, and add new properties like gradients that we can use to make our own controls...

Anyways, if is not possible to use BGRABitmap with that package, we can still make the controls as we was doing to this point.

Check also this other bug report
https://github.com/bgrabitmap/bgragui/issues/4

**Comment by lainz** [comment]
I received a response from the author of the CSS package https://github.com/pst2d/csscontrols/issues/3

Seems that is adding more styling stuff into it.
