### ISSUE TITLE
Another thing about the drawer properties

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgragui#4]
Apart of using or not the CSS package...

I have a new idea as well, is somewhat an idea I already had some time ago.

In this repository https://github.com/bgrabitmap/BGRAJSONStyles
I coded a thing that works like the .css you found on a website, but with BGRABitmap.

The idea is to have string properties that can handle the style properties.

For example for color, instead of using TColor on LCL or Colorty in MSEide, we can use a string that reads the values for example:

`'rgb(100,200,200)'`
or in hex
`'#FFFFFF'`

and for the gradients like is done in a website
https://www.w3schools.com/css/css3_gradients.asp

'background-image: linear-gradient(direction, color-stop1, color-stop2, ...);'

but for our own drawers. Instead of publishing each property in the 'Styles' or 'BGStyles' property, we publish a JSON property, where you can set all the properties from a file, or type them with code, as you wish.

That's another idea for making the drawers.

An advantage of using this, for example say we want to draw the BGRAControls BCButton, it has StateNormal, StateHover, StatePressed, missing StateDisabled and StateFocused.

With JSON styles we can add properties like

```
button:normal {
background-color: "red"
}

button:hover {
background-color: "green"
}

button: disabled {
background-color: "gray"
}

```

That in a plain .json file that's human readable. Instead of messing with the object inspector, we can use that kind of files to theme the controls. Like is done in a website. We can reuse that JSON files between projects, instead of loading styles in the object inspector, just place the file in the project directory and that's all.

Well this is another idea, is for implementing the drawers.

I'm not sure wich way to follow 👎

**Comment by fredvs** [comment]
Hello Lainz.

All that is very new for me.

I need to study all that deeply.

Write you later.

**Comment by lainz** [comment]
Ok.
I'm open to new ideas for the development of this controls. That's why I opened the last two bug reports. Don't want to do the same over and over again, like redoing all the controls just for fun. I want to do something more modern and flexible if I will take the time to do this =)

For example a kind of css file is used too in QT that's one of the biggest C++ IDEs available.
https://doc.qt.io/Qt-5/stylesheet-syntax.html

**Comment by lainz** [comment]
Apart of this, I will take my time to explore the possibilities, so maybe I'm coding on private repositories and then I will share my findings here.

**Comment by circular17** [comment]
Indeed copying the style is then as easy as copying a text file. Some other advantage of having CSS-like files, is that one does not need to have to define the property for each state if it is the same.

```
button {
font-family: Arial
font-size: 15px
}

button:normal {
background-color: "red"
}

button:hover {
background-color: "green"
}

button: disabled {
background-color: "gray"
}
```

**Comment by lainz** [comment]
Yes, that's it. I received a response from the author of the CSS package https://github.com/pst2d/csscontrols/issues/3

Seems that is adding more styling stuff into it.

**Comment by lainz** [comment]
I was thinking all night how can be possible to do this, and I found that is really a neccesity to have a DOM to style, else you need to iterate over all items in the form, if you want to use class selectors for example.

But for just normal states, a self contained CSS-like property for a single control is enough. When combining selectors the thing gets harder, as well as adding / removing classes from a control at runtime.

For that I say that the CSS package is good, it provides that already, so we maybe can create some custom controls based on it.

Check this code, changing the style at runtime as simple as this:

```
Node.ClassList.Add('zselected');
        end else Node.ClassList.Remove('zselected');
```
