### ISSUE TITLE
Missing instruction for mse in readme.md

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgragui#7]
Hello.

It seems that in **Option 1 - Copy** the instruction is missing:

Add `-dBGRABITMAP_USE_MSEGUI` in Project Options > Make > Make options.

And for both **Options 1 and 2**, add in _ProjectOption-Make-Directories_, the directory of 
/bgrabitmap, /bgragui/bgraguicontrols/msegui and /bgragui/bgragui
Also is needed directory of /lazarus/components/lazutils

And for both **Options 1 and 2**, add `-dclass_bridge` in _Project Options > Make > Make options_.

Thanks.

Fre;D

**Comment by lainz** [comment]
Hi, can you edit the readme? You already have access.

**Comment by fredvs** [comment]
Ha, ok, thanks.

Done.
