### ISSUE TITLE
bgragui and /lazarus/components/lazutils/

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgragui#8]
Hello.

What do you think to add in _bgragui_ code or in _BGRABitmap_ code the units needed from _/lazarus/components/lazutils/_?

This to not be obliged to install all Lazarus to be able to compile bgragui.

Fre;D

**Comment by fredvs** [comment]
Ooops, I did try removing directory of /lazarus/components/lazutils/ and it compiles ok.

Or I miss something or you did fix this already and there are no more dependencies to /lazarus/components/lazutils/?

If so, sorry for the noise.

Fre;D

**Comment by circular17** [comment]
Is LazUtils really needed?

**Comment by fredvs** [comment]
It was needed the last time I worked with bgragui + bgrabitmap.
But it was before the Covid, so nothing to compare.

Now it seems that LazUtils is no more needed, no cry when compiling without adding his directory.

So, sorry for the noise (and I will delete the line in readme.md instructions).

**Comment by circular17** [comment]
Ok so that solves it
